env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"
data_base:
  host: localhost
  port: 5433
  user: dargven
  password: root
  name: api